development:
   adapter: mysql
   database: alerta
   username: benitocamela
   password: fuckyeah
   encoding: utf8
   host: localhost

test:
   adapter: mysql
   database: alerta
   username: benitocamela
   password: fuckyeah
   encoding: utf8
   host: localhost

production:
   adapter: mysql
   database: library_production
   username: root
   password: [password]
   host: localhost
